name: Pull changes

on:
  push:
    branches: [ master ]

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script : |
            . $HOME/.profile
            cd "$DEPLOYMENT_DIR"
            CURRENT_BRANCH=$(git branch --show-current)
            [ ${{ github.ref_name }} = "$CURRENT_BRANCH" ] && git pull origin "$CURRENT_BRANCH"
