name: Pull changes

on:
  push:
    branches: [ master ]

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: sora-reader/vps-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

